spring.application.name: core-api
spring.profiles.active: local

spring:
  config:
    import:
      - monitoring.yml
      - db-core.yml
  web.resources.add-mappings: false

api:
  base-path: "/api/v1"

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live

